version: '3.8'

services:
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data



  doc_management_api:
    container_name: doc_management_api
    build: ./app/backend/reference_doc
    env_file:
      - .env
    ports:
      - ${DOC_FASTAPI_PORT}:${DOC_FASTAPI_PORT}

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./data:/data
    
    deploy:
      resources:
        limits:
          memory: 4g # Limit memory to 4GB
          cpus: "2.0" # Limit to 2 CPUs
        reservations:
          memory: 2g # Reserve 2GB of memory
          cpus: "1.0" # Reserve 1 CPU

    depends_on:
      - redis
      - minio
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  frontend_streamlit:
    container_name: frontend_streamlit
    build: ./app/frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - DOC_API_URL=http://doc_management_api:${DOC_FASTAPI_PORT}
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      # - CHAT_API_URL=http://chat_api:${CHAT_FASTAPI_PORT}
    command: ["streamlit", "run", "QA.py", "--server.port", "${FRONTEND_PORT}"]
    depends_on:
      - "doc_management_api"
      # - "chat_api"      
    volumes:
      - ./app/frontend:/app

volumes:
  redis_data:


networks:
  default:
    name: mlops