apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        workload: frontend
      containers:
      - name: frontend
        image: sieucun/llmops-frontend
        ports:
        - containerPort: 8501
        env:
        - name: DOC_API_URL
          value: http://backend-doc:8001
        - name: CHAT_API_URL
          value: http://backend-chat:8002
        - name: NGINX_URL
          value: nginx:80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 80           # Expose the service on port 80 (optional for NodePort services)
    targetPort: 8081    # Forward traffic to the Streamlit application running on port 8081
    nodePort: 30001     # Optional: Specify a NodePort between 30000-32767

