{{- range $serviceName, $config := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
spec:
  selector:
    app: {{ $serviceName }}
  ports:
  - port: {{ $config.port }}
    targetPort: {{ $config.port }}
  type: ClusterIP
{{- end }}
