replicaCount: 2

image:
  repository: your-dockerhub-username/frontend_streamlit
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8501

nodeSelector:
  workload: frontend

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

env:
  DOC_API_URL: http://doc-management-api:8000
  CHAT_API_URL: http://chat-api:8001
