apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image }}
        ports:
        - containerPort: {{ .Values.prometheus.containerPort }}
        volumeMounts:
          - name: prometheus-config
            mountPath: {{ .Values.prometheus.configPath }}
        args:
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus
          - --web.console.libraries=/etc/prometheus/console_libraries
          - --web.console.templates=/etc/prometheus/consoles
          - --storage.tsdb.retention.time=20h
          - --web.enable-lifecycle
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

          items:
          - key: "prometheus.yml"
            path: "prometheus.yml"
          - key: "alert-rules.yml"
            path: "alert-rules.yml"