apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: {{ .Values.prometheus.containerPort }}
      targetPort: {{ .Values.prometheus.containerPort }}
  type: ClusterIP