apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  labels:
    app: cadvisor
spec:
  type: ClusterIP  # Use ClusterIP service type
  ports:
    - port: {{ .Values.cadvisor.containerPort }}       # The port that will be exposed
      targetPort: {{ .Values.cadvisor.containerPort }}  # The port on the container to forward traffic to
  selector:
    app: cadvisor  # This should match the labels of the DaemonSet
