apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        workload: frontend # Aligning with the frontend node pool in Terraform
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        upstream doc_management_api {
            server doc_management_api:8001;
        }

        upstream chat_api {
            server chat_api:8002;
        }

        server {
            listen 80;

            location /upload {
                proxy_pass http://doc_management_api;
            }

            location /remove_document {
                proxy_pass http://doc_management_api;
            }

            location /ws/ {
                proxy_pass http://chat_api;  # Proxy WebSocket traffic to the chat backend
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                chunked_transfer_encoding on;
                proxy_buffering off;
                proxy_cache off;

                # Increase timeouts for long-lived connections
                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
            }

            # If using /test for a specific endpoint
            location /test {
                proxy_pass http://chat_api;
                chunked_transfer_encoding on;
                proxy_buffering off;
                proxy_cache off;
                proxy_http_version 1.1;

                # Increase timeout for long-lived connections (e.g., SSE or WebSockets)
                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
