apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      nodeSelector:
        workload: compute-heavy
      containers:
      - name: chat-api
        image: your-dockerhub-username/chat_api:latest
        ports:
        - containerPort: 8001
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: DOC_API_URL
          value: http://doc-management-api:8000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-api
spec:
  selector:
    app: chat-api
  ports:
  - port: 8001
    targetPort: 8001
