apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        workload: system-services # Aligning with the Terraform setup
      containers:
      - name: redis
        image: redis/redis-stack-server:7.2.0-v6
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_ARGS
          value: "--save 60 1 --loglevel warning" # Example for fine-tuning Redis settings
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
